#!/usr/bin/env bash
# =============================================================================
# SurviveV1 — passwordless sudo for the dashboard's service-restart buttons
#
# The dashboard (running as the service user) needs to restart individual
# services on request. Rather than run the whole app as root, grant ONLY the
# exact `systemctl restart <unit>` commands it needs — no wildcards (a
# `systemctl restart *` grant would let the web app restart sshd, etc.).
#
# The file is validated with `visudo -cf` BEFORE being installed: a syntax
# error in /etc/sudoers.d can lock the machine out of sudo entirely.
#
#   sudo bash scripts/install_sudoers.sh
# =============================================================================
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

GREEN='\033[0;32m'; BLUE='\033[0;34m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${BLUE}[SUDOERS]${NC} $*"; }
ok()    { echo -e "${GREEN}[SUDOERS]${NC} $*"; }
err()   { echo -e "${RED}[SUDOERS]${NC} $*" >&2; }

[[ $EUID -eq 0 ]] || { err "Run with sudo: sudo bash $0"; exit 1; }

# Same service-user resolution as generate_services.sh.
SERVICE_USER="${SURVIVE_SERVICE_USER:-${SUDO_USER:-}}"
[[ -n "$SERVICE_USER" ]] || SERVICE_USER=$(stat -c '%U' "$REPO_DIR")
id "$SERVICE_USER" &>/dev/null || SERVICE_USER="pi"

# Units the dashboard is allowed to restart. Keep in sync with the `unit`
# fields in web/constants.py SERVICES, plus the dashboard's own unit.
UNITS=(kiwix kolibri calibre-web jellyfin martin-tiles ollama survive-dashboard)

SYSTEMCTL="$(command -v systemctl || echo /usr/bin/systemctl)"

# Build one comma-separated Cmnd list of exact commands (no wildcards).
cmds=""
for u in "${UNITS[@]}"; do
    cmds+="${cmds:+, }${SYSTEMCTL} restart ${u}"
done

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<EOF
# Generated by scripts/install_sudoers.sh -- do not edit by hand.
# Lets the SurviveV1 dashboard restart its own services (exact commands only).
${SERVICE_USER} ALL=(root) NOPASSWD: ${cmds}
EOF

DEST="/etc/sudoers.d/survive-dashboard"
if visudo -cf "$TMP" >/dev/null 2>&1; then
    install -m 440 "$TMP" "$DEST"
    ok "Installed $DEST for user '$SERVICE_USER'"
    info "Allowed: systemctl restart {${UNITS[*]}}"
else
    err "Generated sudoers file failed validation -- NOT installed."
    err "Restart buttons will fall back to showing the manual command."
    exit 1
fi
